[paths]

game_files="../gamefiles/limbo/"
support_files="../gamefiles/support_files/"

android_package_code="/fakepath_package_code"
android_external_files="/fakepath_external_files"
android_files="/fakepath_files"
android_obb_dirs=["/fakepath_obb"]
android_source_dirs=["/fakepath_source"]
android_cache="cache/"


[package]

packageName="com.example.package"
versionName="0.1"
mainIntentBundle = {}


[device]

displayWidth=640
displayHeight=480
displayRotation=0



